// <auto-generated />
using System;
using Lab05.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab05.DAL.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251221121154_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab05.DAL.Models.Faculty", b =>
                {
                    b.Property<int>("FacultyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyID"));

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("FacultyID");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("Lab05.DAL.Models.Major", b =>
                {
                    b.Property<int>("FacultyID")
                        .HasColumnType("int");

                    b.Property<int>("MajorID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("FacultyID", "MajorID");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("Lab05.DAL.Models.Student", b =>
                {
                    b.Property<string>("StudentID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AverageScore")
                        .HasColumnType("float");

                    b.Property<int>("FacultyID")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MajorID")
                        .HasColumnType("int");

                    b.HasKey("StudentID");

                    b.HasIndex("FacultyID", "MajorID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Lab05.DAL.Models.Major", b =>
                {
                    b.HasOne("Lab05.DAL.Models.Faculty", "Faculty")
                        .WithMany("Majors")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Lab05.DAL.Models.Student", b =>
                {
                    b.HasOne("Lab05.DAL.Models.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab05.DAL.Models.Major", "Major")
                        .WithMany("Students")
                        .HasForeignKey("FacultyID", "MajorID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Faculty");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("Lab05.DAL.Models.Faculty", b =>
                {
                    b.Navigation("Majors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Lab05.DAL.Models.Major", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
