// <auto-generated />
using Lab06.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab06.DAL.Migrations
{
    [DbContext(typeof(Model1))]
    partial class Model1ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab06.DAL.Models.LoaiSach", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiSachs");

                    b.HasData(
                        new
                        {
                            MaLoai = 1,
                            TenLoai = "Khoa Học"
                        },
                        new
                        {
                            MaLoai = 2,
                            TenLoai = "Y học"
                        },
                        new
                        {
                            MaLoai = 3,
                            TenLoai = "Đời sống"
                        });
                });

            modelBuilder.Entity("Lab06.DAL.Models.Sach", b =>
                {
                    b.Property<string>("MaSach")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<int>("NamXB")
                        .HasColumnType("int");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaSach");

                    b.HasIndex("MaLoai");

                    b.ToTable("Sachs");

                    b.HasData(
                        new
                        {
                            MaSach = "KH0001",
                            MaLoai = 1,
                            NamXB = 2018,
                            TenSach = "Khám phá sự sống"
                        },
                        new
                        {
                            MaSach = "KH0002",
                            MaLoai = 1,
                            NamXB = 2018,
                            TenSach = "Hải dương học"
                        },
                        new
                        {
                            MaSach = "YH0001",
                            MaLoai = 2,
                            NamXB = 2020,
                            TenSach = "Chuẩn đoán và điều trị"
                        });
                });

            modelBuilder.Entity("Lab06.DAL.Models.Sach", b =>
                {
                    b.HasOne("Lab06.DAL.Models.LoaiSach", "LoaiSach")
                        .WithMany("Sachs")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSach");
                });

            modelBuilder.Entity("Lab06.DAL.Models.LoaiSach", b =>
                {
                    b.Navigation("Sachs");
                });
#pragma warning restore 612, 618
        }
    }
}
